#!/bin/bash

LOCK="   Lock"
SLEEP="󰤄   Sleep"
REBOOT="   Reboot"
SHUTDOWN="   Shutdown"
chosen=$(echo -e "$SLEEP\n$REBOOT\n$SHUTDOWN\n$LOCK" | rofi -mesg "󰚥 $HOSTNAME" -dmenu -p "Action:" -config ~/.config/rofi/power-manager/power-manager.rasi)

case $chosen in
    "$SLEEP")
        systemctl suspend
        ;;
    "$LOCK")
        hyprlock
        ;;
    "$REBOOT")
        systemctl reboot
        ;;
    "$SHUTDOWN")
        systemctl poweroff
        ;;
esac
