#!/usr/bin/env bash

HYPRGAMEMODE=$(hyprctl getoption animations:enabled -j | jq -r '.bool')
if [[ "$HYPRGAMEMODE" == "true" ]]; then
    hyprctl eval 'hl.config({
        animations = { enabled = false },
        decoration = {
            shadow = { enabled = false },
            blur = { enabled = false },
            rounding = 0
        },
        general = {
            gaps_in = 0,
            gaps_out = 0,
            border_size = 1
        }
    })'
    notify-send "Game Mode" "Enabled"
else
    hyprctl reload
    notify-send "Game Mode" "Disabled"
fi
