#!/bin/bash

PLAYER="spotify"

if playerctl -p "$PLAYER" status >/dev/null 2>&1; then
    spotify_running=true

    shuffle=$(playerctl -p "$PLAYER" shuffle 2>/dev/null)
    volume=$(playerctl -p "$PLAYER" volume 2>/dev/null)
    volume=$(awk -v v="$volume" 'BEGIN {printf "%.0f%%", v * 100}')
    title=$(playerctl -p "$PLAYER" metadata --format '{{title}} - {{artist}}' 2>/dev/null)

    choice=$(
        printf '%s\n' \
            "󰐊 Play/Pause" \
            "󰒮 Previous" \
            "󰒭 Next" \
            "󰑖 Shuffle [$shuffle]" \
            "󰕾 Volume [$volume]" \
            "󰓓 Kill Spotify" |
        rofi -mesg "$title" -dmenu -theme ~/.config/rofi/media/musicplayer.rasi -p "Spotify"
    )
else
    choice=$(
        printf '%s\n' \
            "󰓓 Launch Spotify" |
        rofi -dmenu -theme ~/.config/rofi/media/musicplayer.rasi -p "Spotify"
    )
fi

case "$choice" in
    "󰐊 Play/Pause")
        playerctl -p "$PLAYER" play-pause
        ;;

    "󰒮 Previous")
        playerctl -p "$PLAYER" previous
        ;;

    "󰒭 Next")
        playerctl -p "$PLAYER" next
        ;;

    "󰑖 Shuffle [$shuffle]")
        playerctl -p "$PLAYER" shuffle Toggle

        new_shuffle=$(playerctl -p "$PLAYER" shuffle 2>/dev/null)

        notify-send "Spotify" "Shuffle: $new_shuffle"
        ;;

    "󰕾 Volume [$volume]")
        new_volume=$(
            printf "%s" "$volume" |
            rofi -dmenu -theme ~/.config/rofi/media/input.rasi -p "Volume " -mesg "           Current: $volume"
        )

        if [[ "$new_volume" =~ ^[0-9]+%?$ ]]; then
            percent="${new_volume%\%}"

            if (( percent >= 0 && percent <= 100 )); then
                playerctl -p "$PLAYER" volume "$(awk -v v="$percent" 'BEGIN {print v / 100}')"
            fi
        fi
        ;;

    "󰓓 Launch Spotify")
        spotify-launcher
        ;;

    "󰓓 Kill Spotify")
        pkill -x spotify
        ;;
esac
